---
title: "LD Akkermansia ASVs"
author: "Katherine Mueller"
date: "8/4/2021"
output: html_document
---

#Load Libraries
```{r}
library(phyloseq)
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
```

#Define Paths
```{r}
LD_mice.rds <- "../../Data/Analysis/LD_mice.rds"
out.dir <- "../../Data/Analysis"
```

Load and check phyloseq object
```{r}
LD_mice.ps = read_rds(LD_mice.rds)
print(LD_mice.ps)
```

```{r}
sample_variables(LD_mice.ps)
```

#Relative Abundance
```{r}
rel.ps <- LD_mice.ps %>%
  transform_sample_counts(function(x) x/sum(x))
```

#Akkermansia ASV Identification
```{r}
akks.ps <- rel.ps %>%
  subset_taxa(Genus == "Akkermansia")
print(akks.ps)
```

#Filter for Akk ASVs at a mean abundance of at least 0.01%
```{r}
mean_cutoff = 0.001
mean_test = function(x) {
  mean(x) >= mean_cutoff
}

akks.0001mean.ps <- akks.ps %>%
  filter_taxa(mean_test, prune = TRUE)
print(akks.0001mean.ps)
```

```{r}
akks0001 <- akks.0001mean.ps %>%
  otu_table() %>%
  as.data.frame()
colnames(akks0001)
```


Double check that none of the other ASVs should be included
```{r}
#get dataframe for akk ASV abundances
all_akks <- akks.ps %>%
  otu_table() %>%
  as.data.frame()

#Make the dataframe long for plotting
akks.long <- all_akks %>%
  gather(ASV, Abundance)

#Plot Akk ASV abundances
akks.boxplot <- akks.long %>%
  ggplot(aes(x = ASV, y = Abundance)) +
  geom_point() +
  geom_jitter()
akks.boxplot
```

It looks like taking more than the initial two wouldn't contribute to anything.